language: ruby
rvm:
- 2.5.0

script: make test

branches:
  only:
  - master

env:
  global:
  - VERSION=`cat version`
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

exclude: [vendor]

before_deploy:
  - git config --local user.name "Travis CI"
  - git config --local user.email "hayden.king@gmail.com"
  - git tag ${VERSION}
  - make deploy

deploy:
  provider: releases
  api_key:
    secure: lYoJQM9DSFbhcIpD74doZrROnvkBLuuATJnmblJYxyYP8uKgondA5Hir1paA/yo32nvVhtcWEoj/UA2e8igrI53DZ7FAmkhj/k8zrraZPUuuswBVUlpYlHYgpH8IP5qHewAKQFj6b0OQQsw6T7HTPLOXi1E1MLCEmf246A//w2621MGUcBufcIbpdAKUlbh3e47BeEAmU7yMDusPZtVtoz42ctLPoFcCtkkL635qBgsOF1RF0qobuK4i6lEIxwbwBibeB0qTgTi//+eMuC6CMCXzW9Ryxvu4wNVK1Y/ZjZmqbr8PQ1Y8VohBIcUU1hM4NuFeI2emqrzUBNqvwV/k6dgXQCi8+89VGVSGlGXGzc/3o50tcOHwb5HKK0UKDG/IyWkFNtN6vWAEXtgJ0wFLjpC6GPzHNCFErD8MzaI0IVHh9ByIHVQVAnbu7sZ4hs9mo0JZxZkMWf7w95DYGTdNMeidecU9PPFQ1FykOHO87BLwWrj/9XOOLWo6CdKMadJeMEvctV5o6QcNlNlDx+cPvRkbrxQ+Aa/FyKhmVvd3o65RHqP86FZJ3MqjH4jeiRT+CuLl5DVez1KaV3bg8boJ3E6UIiJUuKvCU1EgpVksht9Sl4cz9PgqqCfKBREeCUM7V/kNYti8uFbn/wC7+DpLiqnwH5QCT4RMtrXLDn+PvBY=
  file: linktree-$VERSION.tar.bz2
  skip_cleanup: true
  on:
    repo: haydenk/linktree

sudo: false