language: ruby
rvm:
- 2.5.0

script: make test

branches:
  only:
  - master

env:
  global:
  - VERSION=`cat version`

exclude: [vendor]

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: _site
  on:
    branch: master

sudo: false