title: My Link Tree
description: My Custom Link Tree. My Custom Instgram Bio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
image: "/images/23823754_167317707338431_9091876837084102656_n.jpg"
instagram_username: coachhaydenking

# Build settings
markdown: kramdown
sass:
    load_paths:
        - _sass
        - node_modules
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
  - node_modules
  - Makefile
  - _vendor
  - .idea